# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.5
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "src/requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r src/requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "src/requirements.txt" }}
        
      # run tests!
      # this example uses Django's built-in test-runner
      # other common Python testing frameworks include pytest and nose
      # https://pytest.org
      # https://nose.readthedocs.io
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            source chave.conf && python src/__init__.py -nit 84 64 30 112 250 854 -in input/trace/2-eucalyptus-traces/AZ1-trace.txt input/trace/2-eucalyptus-traces/AZ2-trace.txt input/trace/2-eucalyptus-traces/AZ3-trace.txt input/trace/2-eucalyptus-traces/AZ4-trace.txt input/trace/2-eucalyptus-traces/AZ5-trace.txt input/trace/2-eucalyptus-traces/AZ6-trace.txt -az 13 24 7 12 7 8 12 8 31 32 31 32 -ha input/trace/2-eucalyptus-traces/AZ1-trace-plus.txt input/trace/2-eucalyptus-traces/AZ2-trace-plus.txt input/trace/2-eucalyptus-traces/AZ3-trace-plus.txt input/trace/2-eucalyptus-traces/AZ4-trace-plus.txt input/trace/2-eucalyptus-traces/AZ5-trace-plus.txt input/trace/2-eucalyptus-traces/AZ6-trace-plus.txt -alg CHAVE -ca LOCK -ff FFD2I -wt 1 -lock RANDOM -ovc False -cons False -repl False 

      - store_artifacts:
          path: test-reports
          destination: test-reports
          
